algoritmo "Viagem Disney"
// Função : Demonstrar a estrutura condicional e descobrir se você poderia ir à Disney
// Autor : Eduardo Barreto
// Data : 26/11/2021
// Seção de Declarações 
var
   dinheiro: Inteiro
inicio
// Seção de Comandos
   escreva("Você tem R$ ")
   leia(dinheiro)
   
   se(dinheiro > 10000) entao
       escreval("Partiu Disney!")
   senao
       escreval("Chora na rampa, fique em casa!")
   fimSe
fimalgoritmo
