algoritmo "Par ou ímpar condicional"
// Função : Informar se um número é par ou ímpar com condições
// Autor : Eduardo Barreto
// Data : 26/11/2021
// Seção de Declarações 
var
   numero: Inteiro
inicio
// Seção de Comandos 
   escreva("Digite um número: ")
   leia(numero)
   
   se(numero % 2 = 0) entao
       Escreval("O número", numero, " é par!")
   senao
       Escreval("O número", numero, " é ímpar!")
   fimSe
fimalgoritmo
