algoritmo "Repetição conta até 0"
// Função : Demonstrar os laços de repetição com a função ENQUANTO
// Autor : Eduardo Santos Barreto
// Data : 03/12/2021
// Seção de Declarações
var
   contagem: Inteiro
inicio
// Seção de Comandos
   contagem <- 7

   enquanto (contagem >= 0) faca
      escrevaL(contagem)
      contagem <- contagem - 1
   fimEnquanto

   escrevaL("Fim da contagem")
fimalgoritmo

