algoritmo "Tabuada com enquanto"
// Função : Mostra a tabuada de um número informado pelo usuário
// Autor : Eduardo Barreto
// Data : 03/12/2021
// Seção de Declarações
var
   numero, contador: Inteiro
inicio
// Seção de Comandos

   contador <- 0

   escreva("Digite o número: ")
   leia(numero)

   enquanto (contador < 11) faca
      escrevaL(numero, " *", contador, " =", numero*contador)
      contador <- contador + 1
   fimEnquanto

fimalgoritmo
